//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wollsdorf_Spaltwaage.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wollsdorf_Spaltwaage.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Icon ico_Add_1 {
            get {
                object obj = ResourceManager.GetObject("ico_Add_1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ico_Arrow_6 {
            get {
                object obj = ResourceManager.GetObject("ico_Arrow_6", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ico_ArrowDown {
            get {
                object obj = ResourceManager.GetObject("ico_ArrowDown", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ico_ArrowLeft {
            get {
                object obj = ResourceManager.GetObject("ico_ArrowLeft", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ico_ArrowRight {
            get {
                object obj = ResourceManager.GetObject("ico_ArrowRight", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ico_ArrowUp {
            get {
                object obj = ResourceManager.GetObject("ico_ArrowUp", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ico_Delete_2 {
            get {
                object obj = ResourceManager.GetObject("ico_Delete_2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ico_Door {
            get {
                object obj = ResourceManager.GetObject("ico_Door", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ico_Exit {
            get {
                object obj = ResourceManager.GetObject("ico_Exit", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ico_House {
            get {
                object obj = ResourceManager.GetObject("ico_House", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ico_Immense {
            get {
                object obj = ResourceManager.GetObject("ico_Immense", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ico_Light_1 {
            get {
                object obj = ResourceManager.GetObject("ico_Light_1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ico_LightBulb {
            get {
                object obj = ResourceManager.GetObject("ico_LightBulb", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ico_Ok {
            get {
                object obj = ResourceManager.GetObject("ico_Ok", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ico_Pen {
            get {
                object obj = ResourceManager.GetObject("ico_Pen", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ico_PGDown {
            get {
                object obj = ResourceManager.GetObject("ico_PGDown", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ico_PGUp {
            get {
                object obj = ResourceManager.GetObject("ico_PGUp", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ico_Print {
            get {
                object obj = ResourceManager.GetObject("ico_Print", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ico_Report_4 {
            get {
                object obj = ResourceManager.GetObject("ico_Report_4", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ico_Save_1 {
            get {
                object obj = ResourceManager.GetObject("ico_Save_1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ico_Tare {
            get {
                object obj = ResourceManager.GetObject("ico_Tare", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ico_Tare_Large {
            get {
                object obj = ResourceManager.GetObject("ico_Tare_Large", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ico_Tare_Medium {
            get {
                object obj = ResourceManager.GetObject("ico_Tare_Medium", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ico_Yes {
            get {
                object obj = ResourceManager.GetObject("ico_Yes", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ico_Zero {
            get {
                object obj = ResourceManager.GetObject("ico_Zero", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Nullstellen_Transparent {
            get {
                object obj = ResourceManager.GetObject("Nullstellen_Transparent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^XA
        ///^XFR:Wollsdor.ZPL^FS
        ///^FN11^FD@PALNR@^FS
        ///^FN12^FD@ARTNR@^FS
        ///^FN13^FD@STK@^FS
        ///^FN14^FD@GEWICHT@^FS
        ///^FN15^FD@ARTBEZ@^FS
        ///^PQ1^XZ.
        /// </summary>
        internal static string old_sZPL_Data {
            get {
                return ResourceManager.GetString("old_sZPL_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CT~~CD,~CC^~CT~
        ///^XA
        ///^DFR:Wollsdor.ZPL^FS
        ///~TA000~JSN^LT0^MNW^MTD^PON^PMN^LH0,0^JMA^PR3,3^MD20^LRN^CI0
        ///^MMT
        ///^PW1181
        ///^LL1181
        ///^LS0
        ///^FT694,976^A0N,100,98^FB440,1,0^FH\^FN14&quot;@GEWICHT@&quot;^FS
        ///^FT692,832^A0N,100,98^FB441,1,0^FH\^FN13&quot;@STK@&quot;^FS
        ///^FT692,695^A0N,100,98^FB441,1,0^FH\^FN11&quot;@PALNR@&quot;^FS
        ///^FT123,442^A0N,83,81^FB371,1,0^FH\^FN15&quot;@ARTBEZ@&quot;^FS
        ///^FT463,255^A0N,67,67^FB300,1,0^FH\^FN12&quot;@ARTNR@&quot;^FS
        ///^FT97,965^A0N,67,67^FB503,1,0^FH\^FDGEWICHT(weight):^FS
        ///^FT97,813^A0N,67,67^FB441,1,0^FH\^FDST\9ACK (piece [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string old_sZPL_Label {
            get {
                return ResourceManager.GetString("old_sZPL_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CT~~CD,~CC^~CT~
        ///^XA~TA000~JSN^LT0^MNW^MTD^PON^PMN^LH0,0^JMA^PR3,3~SD20^JUS^LRN^CI0^XZ
        ///^XA
        ///^MMT
        ///^PW1181
        ///^LL1181
        ///^LS0
        ///^FT107,1086^A0N,58,57^FH\^FD@DATE@^FS
        ///^FT694,976^A0N,100,98^FH\^FD@GEW@^FS
        ///^FT692,832^A0N,100,98^FH\^FD@STK@^FS
        ///^FT692,695^A0N,100,98^FH\^FD@PALNR@^FS
        ///^FT123,442^A0N,83,81^FH\^FD@ARTBEZ@^FS
        ///^FT127,534^A0N,67,67^FH\^FD@ARTNR@^FS
        ///^FT242,179^A0N,75,74^FH\^FD@GRUPPENN2@^FS
        ///^FT241,99^A0N,75,74^FH\^FD@GRUPPENN1@^FS
        ///^FT549,1090^A0N,67,67^FH\^FDU:________________^FS
        ///^FT97,965^A0N,67,6 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sZPL_Data {
            get {
                return ResourceManager.GetString("sZPL_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CT~~CD,~CC^~CT~
        ///^XA
        ///^DFE:Wollsdor.ZPL^FS
        ///~TA000~JSN^LT0^MNW^MTD^PON^PMN^LH0,0^JMA^PR3,3^MD20^LRN^CI0
        ///^MMT
        ///^PW1181
        ///^LL1181
        ///^LS0
        ///^FT107,1086^A0N,58,57^FB416,1,0^FH\^FN18&quot;@DATE@&quot;^FS
        ///^FT694,976^A0N,100,98^FB440,1,0^FH\^FN16&quot;@GEW@&quot;^FS
        ///^FT692,832^A0N,100,98^FB441,1,0^FH\^FN15&quot;@STK@&quot;^FS
        ///^FT692,695^A0N,100,98^FB441,1,0^FH\^FN13&quot;@PALNR@&quot;^FS
        ///^FT123,442^A0N,83,81^FB926,1,0^FH\^FN17&quot;@ARTBEZ@&quot;^FS
        ///^FT127,534^A0N,67,67^FB300,1,0^FH\^FN14&quot;@ARTNR@&quot;^FS
        ///^FT242,179^A0N,75,74^FB825,1,0^FH\^FN12&quot;@GRUPPENN2@&quot;^FS
        ///^ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sZPL_Label {
            get {
                return ResourceManager.GetString("sZPL_Label", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Tarieren_Transparent {
            get {
                object obj = ResourceManager.GetObject("Tarieren_Transparent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
